### ISSUE TITLE
Share link not working for new, unpublished BlogPost

### ISSUE THREAD

**Issue by dbraun-ascendium** [silverstripe-labs/silverstripe-sharedraftcontent#112]
When creating a new, unpublished BlogPost and adding content block, the share link will not display the content of the (published) content block. I've tested this with a non-blog post page type using a content block. In that case sharing a draft works works.

As a work around, I've published and immediately unpublished the new BlogPost. After that, sharing the draft block content works.

## PRs
- https://github.com/silverstripe/silverstripe-blog/pull/727

**Comment by obj63mc** [comment]
When testing this, it appears that if the publish date is set in the future for the blog post, the shared draft content won't show any of the content blocks or other content.  If I set the publish date in the past on a new post and save a draft and do the 'share' it will then show fine.

**Comment by dbraun-ascendium** [comment]
@obj63mc thanks for that info! I've verified that that is indeed the case. In my case, I could set it for up to 4 hours in the future, but beyond that, the share link would not show content block content.

**Comment by sabina-talipova** [comment]
PRs merged. It will be automatically tagged. Close.
