### ISSUE TITLE
Composer 2.0 - RemoveExpiredShareTokens class does not comply with PSR4 autoloading

### ISSUE THREAD

**Issue by obj63mc** [silverstripe-labs/silverstripe-sharedraftcontent#127]
With the release of composer 2.0 coming up they are providing warnings on classes not in properly structured folders for their namespaces.

The warning provided when this package is installed is the following - 

> Deprecation Notice: Class SilverStripe\ShareDraftContent\Tasks\RemoveExpiredShareTokens located in ./vendor/silverstripe/sharedraftcontent/src/Tasks/RemoveExpiredShareTokensTask.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.

**Comment by emteknetnz** [comment]
Fixed in https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/129

**Comment by brynwhyman** [comment]
Fixed in #129
