### ISSUE TITLE
Feature Request: Extend ShareTokenLink

### ISSUE THREAD

**Issue by jakxnz** [silverstripe-labs/silverstripe-sharedraftcontent#134]
Our project needs to extend ShareTokenLink so that we can modify the URL to factor for additional parameters, such as fluent locales.

**Comment by maxime-rainville** [comment]
Good idea. Are you planning on opening a PR based on https://github.com/codecraft/silverstripe-sharedraftcontent/commit/64d46ae8fd83fe706146f76f01d6dbef8d8c844b ?

**Comment by jakxnz** [comment]
Yep. Sorry, should have mentioned this issue in the PR too. Thanks @maxime-rainville

**Comment by maxime-rainville** [comment]
Fixed by #135.
