### ISSUE TITLE
BUG: updateGrant() method throws an Exception when there is no active Controller

### ISSUE THREAD

**Issue by chrispenny** [silverstripe-labs/silverstripe-sharedraftcontent#173]
`ShareDraftContentFileShortcodeProviderExtension::updateGrant()`:

The following code does not consider that we might not have an active Controller when this method is called:
```php
$session = $session = Controller::curr()->getRequest()->getSession();
```

Result:
```
Call to a member function getRequest() on null
```

I haven't dug into the exact reasons for why this method might be called outside of the context of a Request, but it seems to happen often when using the Silverstripe Search Service module and reindexing items.

I will work on a PR shortly.

**Comment by NightJar** [comment]
Looks like this wasn't linked to auto-close on PR merge.
