### ISSUE TITLE
Click on "Share" button and nothing happen

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe-labs/silverstripe-sharedraftcontent#184]
### Description
We user clicks on "Share" button and request is sent to back end, back end returns correct link, but nothing happen on front end and user doesn't have ability to copy link.

### Steps to reproduce issue
- I go to "/admin/pages"
- I click on "Any page" in the tree
- I press the "Share" button 
- Then I should see "Share draft content", but nothing happen 

### AC's
- [ ] When I click on "Share" button then I should see popup element with "Share draft content" and link
- [ ] Behat tests are passed

### PRs

**Comment by maxime-rainville** [comment]
Might be fixed once @GuySartorelli upgrades JS for this module.

**Comment by GuySartorelli** [comment]
This will be fixed by https://github.com/silverstripe/silverstripe-sharedraftcontent/pull/186 which is part of https://github.com/silverstripeltd/product-issues/issues/644
