### ISSUE TITLE
Timeout loading any preview (memory limit)

### ISSUE THREAD

**Issue by mylesthedev** [silverstripe-labs/silverstripe-sharedraftcontent#221]
### Module version(s) affected

2.6.0

### Description

We have a site that's running SilverStripe 4.11 using this module (2.6.0). However on pretty much all pages apart from the home page the server runs out of memory (has a sufficient amount).

The page loads fine when viewing the live URL or if you view the draft in the CMS using split mode etc.

Is there something that this module does that might need to be configured?

### How to reproduce

Copy preview URL and wait for website 500 error.

### Additional Context

Apache + PHP 8.1

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
You've mentioned this affects 2.6.0 - when you reproduced this in a fresh installation, did you use the latest (2.9.5) version in the 2.x release line of this module?

> Copy preview URL and wait for website 500 error.

This is not sufficient setup steps for me to reproduce this when running the module in version 2.9.5. Please provide more information.

**Comment by GuySartorelli** [comment]
There's not enough information here for me to reproduce the problem, and there hasn't been any response, so I'm going to close it now.
If you provide further details that will allow me to reproduce the error I'll be happy to reopen the issue.

**Comment by NightJar** [comment]
It sounds a lot like this internal redirect issue Myles - there is a recent merge of a PR to fix it. Perhaps upgrading will resolve your issue too :)
https://github.com/silverstripe/silverstripe-sharedraftcontent/issues/213
