### ISSUE TITLE
Share link is broken in preview mode

### ISSUE THREAD

**Issue by flashbackzoo** [silverstripe-labs/silverstripe-sharedraftcontent#23]
![share-error](https://cloud.githubusercontent.com/assets/878176/7576246/b7226110-f88f-11e4-8c36-281582bc4fc4.png)

This is happening because preview mode is handled by a different controller than edit mode. The module include LeftAndMain_ViewModeSelector.ss is included by both CMSMain_EditForm.ss and LeftAndMain_SilverStripeNavigator.ss templates, so is actually in the page twice.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe-labs/silverstripe-sharedraftcontent/commit/5e46241adacaae0192de598777bd2f6a038f76b9
