### ISSUE TITLE
Share draft button broken in 3.2

### ISSUE THREAD

**Issue by scott1702** [silverstripe-labs/silverstripe-sharedraftcontent#31]
Styling of share draft button is broken in 3.2

![image](https://cloud.githubusercontent.com/assets/10215604/7673799/744b0d5e-fd6e-11e4-959f-a781fb7fa563.png)

**Comment by flashbackzoo** [comment]
It's caused by this https://github.com/silverstripe/silverstripe-framework/commit/730c4d37

`.chzn-container` gets set to `display: block` on line 226.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-framework/pull/4203
