### ISSUE TITLE
BUG change view mode icon hidden in 3.3.0-beta1

### ISSUE THREAD

**Issue by muskie9** [silverstripe-labs/silverstripe-sharedraftcontent#52]
The button is still there and clickable, there's just no icon.

Clean 3.3.0-beta1 install:
![screen shot 2015-12-23 at 8 58 05 am](https://cloud.githubusercontent.com/assets/870751/11978745/7eafc1e0-a953-11e5-8fd7-ef6a926633ce.png)

Same install with sharedraftcontent installed (issue seen in `1.0.3` and `dev-master`):
![screen shot 2015-12-23 at 8 59 50 am](https://cloud.githubusercontent.com/assets/870751/11978793/c3d77786-a953-11e5-92b6-642e9d15c122.png)

**Comment by flashbackzoo** [comment]
Fixed https://github.com/silverstripe-labs/silverstripe-sharedraftcontent/commit/f1a537a0946eca6755488d1a93d2749d22bee4b6
